- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.0
  with:
    host: ${{ secrets.EC2_PUBLIC_IP }}
    username: ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      docker-compose down
      docker-compose up -d
